-- ایجاد اسکیما (در صورت نیاز)
CREATE SCHEMA IF NOT EXISTS trade;

-- ایجاد جدول account
CREATE TABLE IF NOT EXISTS trade.account (
    account_login TEXT PRIMARY KEY,
    account_trade_mode TEXT,
    account_leverage INTEGER,
    account_limit_orders INTEGER,
    account_margin_so_mode TEXT,
    account_trade_allowed BOOLEAN,
    account_trade_expert BOOLEAN,
    account_margin_mode TEXT,
    account_currency_digits INTEGER,
    account_fifo_close BOOLEAN,
    account_hedge_allowed BOOLEAN,
    account_balance NUMERIC(15, 5),
    account_credit NUMERIC(15, 5),
    account_profit NUMERIC(15, 5),
    account_equity NUMERIC(15, 5),
    account_margin NUMERIC(15, 5),
    account_margin_free NUMERIC(15, 5),
    account_margin_so_call NUMERIC(15, 5),
    account_margin_so_so NUMERIC(15, 5),
    account_margin_initial NUMERIC(15, 5),
    account_margin_maintenance NUMERIC(15, 5),
    account_assets NUMERIC(15, 5),
    account_liabilities NUMERIC(15, 5),
    account_commission_blocked NUMERIC(15, 5),
    account_name VARCHAR(100),
    account_server VARCHAR(100),
    account_currency VARCHAR(10),
    account_company VARCHAR(100)
);

-- ایجاد جدول symbol
CREATE TABLE IF NOT EXISTS trade.symbol (
    symbol_name TEXT PRIMARY KEY,
    symbol_subscription_delay BOOLEAN,
    symbol_sector TEXT,
    symbol_industry TEXT,
    symbol_custom BOOLEAN,
    symbol_chart_mode TEXT,
    symbol_digits INTEGER,
    symbol_spread_float BOOLEAN,
    symbol_ticks_bookdepth INTEGER,
    symbol_trade_calc_mode TEXT,
    symbol_trade_mode TEXT,
    symbol_trade_stops_level INTEGER,
    symbol_trade_freeze_level INTEGER,
    symbol_trade_exemode TEXT,
    symbol_swap_mode TEXT,
    symbol_swap_rollover3days TEXT,
    symbol_margin_hedged_use_leg BOOLEAN,
    symbol_expiration_mode INTEGER,
    symbol_filling_mode INTEGER,
    symbol_order_mode INTEGER,
    symbol_order_gtc_mode TEXT,
    symbol_option_mode TEXT,
    symbol_option_right TEXT
);

-- ایجاد جدول symbolprice
CREATE TABLE IF NOT EXISTS trade.symbolprice (
    account_login TEXT,
    symbol_name TEXT,
    symbol_time TIMESTAMPTZ NOT NULL,
    symbol_background_color TEXT,
    symbol_exist BOOLEAN,
    symbol_select BOOLEAN,
    symbol_visible BOOLEAN,
    symbol_session_deals INTEGER,
    symbol_session_buy_orders INTEGER,
    symbol_session_sell_orders INTEGER,
    symbol_volume INTEGER,
    symbol_volumehigh INTEGER,
    symbol_volumelow INTEGER,
    symbol_time_msc TIMESTAMPTZ,
    symbol_spread INTEGER,
    symbol_expiration_time TIMESTAMPTZ,
    symbol_bid NUMERIC(15, 5),
    symbol_bidhigh NUMERIC(15, 5),
    symbol_bidlow NUMERIC(15, 5),
    symbol_ask NUMERIC(15, 5),
    symbol_askhigh NUMERIC(15, 5),
    symbol_asklow NUMERIC(15, 5),
    symbol_last NUMERIC(15, 5),
    symbol_lasthigh NUMERIC(15, 5),
    symbol_lastlow NUMERIC(15, 5),
    symbol_volume_real NUMERIC(15, 5),
    symbol_volumehigh_real NUMERIC(15, 5),
    symbol_volumelow_real NUMERIC(15, 5),
    symbol_option_strike NUMERIC(15, 5),
    symbol_trade_tick_value NUMERIC(15, 5),
    symbol_trade_tick_value_profit NUMERIC(15, 5),
    symbol_trade_tick_value_loss NUMERIC(15, 5),
    symbol_trade_accrued_interest NUMERIC(15, 5),
    symbol_trade_face_value NUMERIC(15, 5),
    symbol_trade_liquidity_rate NUMERIC(15, 5),
    symbol_swap_long NUMERIC(15, 5),
    symbol_swap_short NUMERIC(15, 5),
    symbol_swap_sunday NUMERIC(15, 5),
    symbol_swap_monday NUMERIC(15, 5),
    symbol_swap_tuesday NUMERIC(15, 5),
    symbol_swap_wednesday NUMERIC(15, 5),
    symbol_swap_thursday NUMERIC(15, 5),
    symbol_swap_friday NUMERIC(15, 5),
    symbol_swap_saturday NUMERIC(15, 5),
    symbol_session_volume NUMERIC(15, 5),
    symbol_session_turnover NUMERIC(15, 5),
    symbol_session_interest NUMERIC(15, 5),
    symbol_session_buy_orders_volume NUMERIC(15, 5),
    symbol_session_sell_orders_volume NUMERIC(15, 5),
    symbol_session_open NUMERIC(15, 5),
    symbol_session_close NUMERIC(15, 5),
    symbol_session_aw NUMERIC(15, 5),
    symbol_session_price_settlement NUMERIC(15, 5),
    symbol_session_price_limit_min NUMERIC(15, 5),
    symbol_session_price_limit_max NUMERIC(15, 5),
    symbol_price_change NUMERIC(15, 5),
    symbol_price_volatility NUMERIC(15, 5),
    symbol_price_theoretical NUMERIC(15, 5),
    symbol_price_delta NUMERIC(15, 5),
    symbol_price_theta NUMERIC(15, 5),
    symbol_price_gamma NUMERIC(15, 5),
    symbol_price_vega NUMERIC(15, 5),
    symbol_price_rho NUMERIC(15, 5),
    symbol_price_omega NUMERIC(15, 5),
    symbol_price_sensitivity NUMERIC(15, 5),
    PRIMARY KEY (
        account_login,
        symbol_name,
        symbol_time
    ),
    FOREIGN KEY (account_login) REFERENCES trade.account (account_login),
    FOREIGN KEY (symbol_name) REFERENCES trade.symbol (symbol_name)
);
